# https://github.com/jhao104/proxy_pool
# 上述项目是本项目使用的代理池，原项目超级棒，而且在使用教学上也可以说是相当详细。
# 一般来说将上述项目clone下来，在本机运行就可以了，如果想要自己配置一个服务器24小时的更新代理的话也可以将上述项目放到服务器上跑
# 但要注意如果是放到服务器上跑，记得把下面的host改成自己服务器的公网IP

# 主机地址，如果仅是在本机跑的话就改成127.0.0.1
host: 127.0.0.1
# 代理池接口端口，这里使用的是项目的默认端口
port: 5010
# 是否启用ip代理池，如果置为False，那么将会使用原生的requests，而非封装后的ip代理池
is_proxy: False